backend:
  name: github
  repo: elitedigideals-web/techwavehub
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    delete: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Draft, name: draft, widget: boolean, default: false}
      - {label: Tags, name: tags, widget: list}
      - {label: Body, name: body, widget: markdown}
